### ISSUE TITLE
Ability to set border colour

### ISSUE THREAD

**Issue by limpep** [Akashkamble/RevealSwitch#1]
Hi great job, 

Would it be possible to add the ability to customise the border colour? Thanks.

**Comment by Akashkamble** [comment]
I will try to implement that in next release :wink:

**Comment by limpep** [comment]
Awesome, thank you.

**Comment by Akashkamble** [comment]
Added functionality to display the border. Check the updated README

**Comment by limpep** [comment]
@Akashkamble Thank you very much.
